# Generated by Django 4.2.18 on 2025-02-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Duration in minutes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('follow-up', 'Follow-up Needed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('phone_calls', models.ManyToManyField(blank=True, related_name='leads', to='myapp.phonecall')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.lead')),
                ('phone_calls', models.ManyToManyField(blank=True, related_name='appointments', to='myapp.phonecall')),
            ],
        ),
    ]
