# Generated by Django 4.2.18 on 2025-02-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_info',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
