# Generated by Django 4.2.18 on 2025-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_lead_contact_info_lead_created_at_lead_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='disposition',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up'), ('voicemail', 'Voicemail'), ('no_answer', 'No Answer')], max_length=20, null=True),
        ),
    ]
